spring:
  application:
    name: ${SPRING_APP_NAME:app-bank}
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/my-bank
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  logging:
    pattern:
      console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'
    file:
      name: app.log
    level:
      root: warn
      io:
        github:
          my-api: trace
      org:
        springframework:
          web: debug
          security: trace
  # trace
  # debug
  # info
  # warn
  # error
  springdoc:
    override-with-generic-response: false
logging:
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
  log4j2:
    pattern:
      console: ${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:2m}